# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/piplinecpu/pipeline/pipeline.srcs/sources_1/ip/irom/irom.xci
# IP: The module: 'irom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/piplinecpu/pipeline/pipeline.srcs/sources_1/ip/irom/irom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'irom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/piplinecpu/pipeline/pipeline.srcs/sources_1/ip/irom/irom.xci
# IP: The module: 'irom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/piplinecpu/pipeline/pipeline.srcs/sources_1/ip/irom/irom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'irom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
