## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 20.000 -name sys_clk_pin -waveform {0.000 10.000} -add [get_ports clk]

## Switches
set_property PACKAGE_PIN V17 [get_ports {switch[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[0]}]
set_property PACKAGE_PIN V16 [get_ports {switch[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[1]}]
set_property PACKAGE_PIN W16 [get_ports {switch[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[2]}]
set_property PACKAGE_PIN W17 [get_ports {switch[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[3]}]
set_property PACKAGE_PIN W15 [get_ports {switch[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[4]}]
set_property PACKAGE_PIN V15 [get_ports {switch[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[5]}]
set_property PACKAGE_PIN W14 [get_ports {switch[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[6]}]
set_property PACKAGE_PIN W13 [get_ports {switch[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[7]}]
set_property PACKAGE_PIN V2 [get_ports {switch[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[8]}]
set_property PACKAGE_PIN T3 [get_ports {switch[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[9]}]
set_property PACKAGE_PIN T2 [get_ports {switch[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[10]}]
set_property PACKAGE_PIN R3 [get_ports {switch[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[11]}]
set_property PACKAGE_PIN W2 [get_ports {switch[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[12]}]
set_property PACKAGE_PIN U1 [get_ports {switch[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[13]}]
set_property PACKAGE_PIN T1 [get_ports {switch[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[14]}]
set_property PACKAGE_PIN R2 [get_ports {switch[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[15]}]


## LEDs
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property PACKAGE_PIN V3 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property PACKAGE_PIN W3 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property PACKAGE_PIN U3 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property PACKAGE_PIN P3 [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property PACKAGE_PIN N3 [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property PACKAGE_PIN P1 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property PACKAGE_PIN L1 [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]

##7 segment display
set_property PACKAGE_PIN V7 [get_ports {ca[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ca[0]}]
set_property PACKAGE_PIN U7 [get_ports {ca[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ca[1]}]
set_property PACKAGE_PIN V5 [get_ports {ca[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ca[2]}]
set_property PACKAGE_PIN U5 [get_ports {ca[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ca[3]}]
set_property PACKAGE_PIN V8 [get_ports {ca[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ca[4]}]
set_property PACKAGE_PIN U8 [get_ports {ca[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ca[5]}]
set_property PACKAGE_PIN W6 [get_ports {ca[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ca[6]}]
set_property PACKAGE_PIN W7 [get_ports {ca[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ca[7]}]

set_property PACKAGE_PIN U2 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]

##Buttons
set_property PACKAGE_PIN U18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN T18 [get_ports {keys[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[0]}]
set_property PACKAGE_PIN W19 [get_ports {keys[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[1]}]
set_property PACKAGE_PIN T17 [get_ports {keys[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[2]}]
set_property PACKAGE_PIN U17 [get_ports {keys[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[3]}]



#create_generated_clock -name mclk -source [get_ports *clk*] -divide_by 1000 [get_nets mclk]

